#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : EGLM03 Modern Control Systems  # The title of the book. Will be placed in the left navbar.
author                      : Dr Chris P. Jobling  # The author of the book
copyright                   : "Swansea University (2019-2021)"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo


email: c.p.jobling@swansea.ac.uk
description: >-
  Notes and example programmes to accompany the module.

# Execution settings
execute:
    execute_notebooks: cache
    cache: ""
    exclude_patterns: [_build, Thumbs.db, .DS_Store, .github, "*.ipynb_checkpoints"]

repository:
    url: https://github.com/cpjobling/eglm03-textbook
    path_to_book: ""
    branch: master

html:
    baseurl: https://cpjobling.github.io/eglm03-textbook/ 
    use_edit_page_button: true
    use_repository_button: true
    use_issues_button: true
    favicon: ""
    extra_footer: |
      This page was created by 
      <a href="https://www.swansea.ac.uk/staff/engineering/c.p.jobling/">
        Dr Chris P. Jobling
      </a> 
      for 
      <a href="https://www.swansea.ac.uk">
        Swansea University
      </a>.
    google_analystics_id: ""
    home_page_in_navbar: true
    extra_navbar: |
      Powered by 
       <a href="https://jupyterbook.org">
        Jupyter Book
      </a>

colab_default: false
sphinx:
  config:
    html_extra_path: ['_assets']
    exclude_patterns: ['**/README.md','portfolio','README.md','LICENSE.md']
    linkcheck_ignore: [r'https://sp.ebrary.com/Shibboleth.sso', r'https://ebookcentral.proquest.com/', r'https://iss-openathensla-runtime.swan.ac.uk']
    parse:
      myst_extended_syntax: true